### ISSUE TITLE
panic: index out of range

### ISSUE THREAD

**Issue by azdagron** [praetorian-inc/gokart#2]
OS: macOS Big Sur (11.5.1)
GoKart Version: 0.1.0
Config: default
Target: github.com/spiffe/spire

Decided to give this a whirl against github.com/spiffe/spire but unfortunately hit a panic.

```
$ go install github.com/praetorian-inc/gokart@latest
go: downloading github.com/praetorian-inc/gokart v0.1.0
go: downloading github.com/lithammer/dedent v1.1.0
go: downloading github.com/owenrumney/go-sarif v1.0.11
go: downloading github.com/segmentio/fasthash v1.0.3
go: downloading golang.org/x/tools v0.1.2
go: downloading github.com/zclconf/go-cty v1.8.4
$ git clone https://github.com/spiffe/spire
$ cd spire
$ gokart scan .
Using default analyzers config found at "~/.gokart/analyzers.yml".
No existing analyzers.yml file found - writing default to ~/.gokart/analyzers.yml

Revving engines VRMMM VRMMM
3...2...1...Go!
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/praetorian-inc/gokart/util.OutputFinding(0xc001acaf60, 0x2f, 0xc005a53e80, 0x7a, 0xc00205b680, 0x4a, 0x48, 0xc001acaf90, 0x28, 0x0, ...)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/util/finding.go:54 +0x116f
github.com/praetorian-inc/gokart/analyzers.Scan(0xc000074330, 0x1, 0x1)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/analyzers/scan.go:128 +0x5bd
github.com/praetorian-inc/gokart/cmd.glob..func1(0x16dcd00, 0xc000074330, 0x1, 0x1)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/cmd/scan.go:53 +0x1ca
github.com/spf13/cobra.(*Command).execute(0x16dcd00, 0xc000074300, 0x1, 0x1, 0x16dcd00, 0xc000074300)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x16dca80, 0xc000000180, 0xc00016df78, 0x1006a25)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/praetorian-inc/gokart/cmd.Execute(...)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/cmd/root.go:61
main.main()
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/main.go:38 +0x32
```

**Comment by isp1r0** [comment]
Thanks @azdagron - I reproduced the bug here and it should be a small fix.

Can you verify that it works as expected if you run without the path '.' argument?
```shell
gokart scan
```
Or from outside the current directory?

```shell
gokart scan spire/
```

**Comment by azdagron** [comment]
Panic exists in both of those situations.

```
$ gokart scan spire
Using default analyzers config found at "~/.gokart/analyzers.yml".

Revving engines VRMMM VRMMM
3...2...1...Go!
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/praetorian-inc/gokart/util.OutputFinding(0xc000a2ab70, 0x2f, 0xc0040ea900, 0x7a, 0xc0022c5680, 0x4a, 0x48, 0xc000a2aba0, 0x28, 0x0, ...)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/util/finding.go:54 +0x116f
github.com/praetorian-inc/gokart/analyzers.Scan(0xc000119f80, 0x1, 0x1)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/analyzers/scan.go:128 +0x5bd
github.com/praetorian-inc/gokart/cmd.glob..func1(0x16dcd00, 0xc000119f80, 0x1, 0x1)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/cmd/scan.go:53 +0x1ca
github.com/spf13/cobra.(*Command).execute(0x16dcd00, 0xc000119f50, 0x1, 0x1, 0x16dcd00, 0xc000119f50)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x16dca80, 0xc000000180, 0xc00016df78, 0x1006a25)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/praetorian-inc/gokart/cmd.Execute(...)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/cmd/root.go:61
main.main()
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/main.go:38 +0x32
$ cd spire
$ gokart scan
Using default analyzers config found at "~/.gokart/analyzers.yml".

Revving engines VRMMM VRMMM
3...2...1...Go!
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/praetorian-inc/gokart/util.OutputFinding(0xc002195350, 0x2f, 0xc001363700, 0x7a, 0xc00239d680, 0x4a, 0x48, 0xc002195380, 0x28, 0x0, ...)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/util/finding.go:54 +0x116f
github.com/praetorian-inc/gokart/analyzers.Scan(0xc0001122c0, 0x1, 0x1)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/analyzers/scan.go:128 +0x5bd
github.com/praetorian-inc/gokart/cmd.glob..func1(0x16dcd00, 0xc0001122c0, 0x1, 0x1)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/cmd/scan.go:53 +0x1ca
github.com/spf13/cobra.(*Command).execute(0x16dcd00, 0x170f698, 0x0, 0x0, 0x16dcd00, 0x170f698)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x16dca80, 0xc000000180, 0xc0001e5f78, 0x1006a25)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/redacted/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/praetorian-inc/gokart/cmd.Execute(...)
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/cmd/root.go:61
main.main()
	/redacted/go/pkg/mod/github.com/praetorian-inc/gokart@v0.1.0/main.go:38 +0x32
```

**Comment by michaelweber** [comment]
This should be fixed in `main` via https://github.com/praetorian-inc/gokart/pull/5 - can you confirm this works?

**Comment by azdagron** [comment]
Happy to!

**Comment by azdagron** [comment]
Seems to be fixed!

```
$ gokart scan
Using config found at /Users/azdagron/.gokart/analyzers.yml

Revving engines VRMMM VRMMM
3...2...1...Go!

Race Complete! Analysis took 9.036793335s and 2961 Go files were scanned (including imported packages)
GoKart found 0 potentially vulnerable functions
```

**Comment by michaelweber** [comment]
Excellent! Closing out this issue, we'll cut a bugfix release for this as well.

Cheers!
Mike
